### ISSUE TITLE
谢谢 ，不过最好有一个使用的demo

### ISSUE THREAD

**Issue by yanggg1133** [jiezongnewstar/MinaManager#2]
谢谢 ，不过最好有一个使用的demo

**Comment by jiezongnewstar** [comment]
no server for test , sorry，you can test with your server friends

**Comment by yanggg1133** [comment]
不是server 。就是MainActivity这里如何调用，server.用一些tcp 工具 会自动生成一个server的。我这叫tcp&udp测试工具

**Comment by yanggg1133** [comment]
你看
package com.ij.minamanager;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
没有调用的方法啊

**Comment by jiezongnewstar** [comment]
start  or  bindService

**Comment by Xiangjinxiu** [comment]
Manifest没有注册service，本地广播没接收，ConnectionConfig没有调用，service没启动。

**Comment by jiezongnewstar** [comment]
那...
